avtenta_mail:
    resource: "@AvtentaMailBundle/Controller/"
    type:     annotation
    prefix:   /mail

avtenta_site:
    resource: "@AvtentaSiteBundle/Controller/"
    type:     annotation
    prefix:   /site

avtenta_rest:
    type: rest
    prefix: /api
    resource: "@AvtentaRestBundle/Resources/config/routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc